crazyflies:
- channel: 100
  id: 1
  initialPosition: [0.5, 0.5, 0.0]
  type: default
  
- channel: 100
  id: 2
  initialPosition: [0.5, 3.0, 0.0]
  type: default
  
- channel: 100
  id: 3
  initialPosition: [0.5, 5.5, 0.0]
  type: default

- channel: 100
  id: 4
  initialPosition: [3.5, 0.5, 0.0]
  type: default
