# PARAMETERS FOR GSL_GADEN #
# ===================== #
gaden_environment:
  ros__parameters:
    verbose: false
    wait_preprocessing: false   # wait for the ok from gaden_preprocessing before running
    fixed_frame: "map"

    # Plot CAD models (Collada format .dae)3
    CAD_models: 
      - "!color [0.92, 0.96, 0.96]"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/10x6_walls.dae"
      - "!color [0.96, 0.17, 0.3]"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/10x6_door_left.dae"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/10x6_door_right.dae"

    # Plot 3D OccupancyGridmap
    occupancy3D_data: "$(var pkg_dir)/scenarios/$(var scenario)/OccupancyGrid3D.csv"

    # Plot gas sources
    number_of_sources: 1
    source_0_position_x: $(var source_x)
    source_0_position_y: $(var source_y)
    source_0_position_z: $(var source_z)
    source_0_scale: 0.2
    source_0_color: [0.0, 1.0, 0.0] 

# ================
gaden_player:
  ros__parameters:
    verbose: false
    player_freq: 5.0         ### (Hz) Freq for loading the simulation log_files
    initial_iteration: 0
    num_simulators: 1        ### Number of simulations to load [1-inf] (useful for multiple sources and gases)

    # Data from the "filament_simulator" pkg. Multiple sources can be set here
    simulation_data_0: "$(var pkg_dir)/scenarios/$(var scenario)/gas_simulations/dynamic/FilamentSimulation_gasType_0_sourcePosition_1.50_3.00_0.75"
    occupancyFile: "$(var pkg_dir)/scenarios/$(var scenario)/OccupancyGrid3D.csv"

    # Loop options        
    allow_looping: true
    loop_from_iteration: 0
    loop_to_iteration: 1499
